# This file was generated by GoReleaser. DO NOT EDIT.
cask "nexo" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ef2c96058ad839189664a29247e7dd3d3fafaf15aafe5f1f0ae845092af055fb"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a2399d9097acc54cbd1f19914fce6e5d1bb1d5aa02ecfe68347e4cae4d81f71"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4078fb783345869fed9a59e948f5b4279deebe4417ee07a8cb56b43236d9536"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "303bebc649e353b753190904c123ed40e83769f30e6cf4d65ea981aa74acfb58"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nexo"
  desc "Package manager for AI development assets — skills, plugins and MCP servers"
  homepage "https://github.com/melvicsosa/nexo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nexo"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nexo"]
    end
  end

  # No zap stanza required

end
