# This file was generated by GoReleaser. DO NOT EDIT.
cask "nexo" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "4fc0d2cd3d2e4e1bd78dac261b94644ef192c873fa9234c7cfb40f9a8c6dd2ea"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "73ce35770bd7f3761313676308b0e1f79e049b3757ca9f4d66294fd82ab37511"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a86260ad8603e5dbc8e10df16125c145be4387df3ab69187e30b3a026beda14"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "edffe4855dcb715a2a3b78698dd06349c8aae0516d307d8bc70f250af39a8e25"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nexo"
  desc "Package manager for AI development assets — skills, plugins and MCP servers"
  homepage "https://github.com/melvicsosa/nexo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nexo"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nexo"]
    end
  end

  # No zap stanza required

end
