# This file was generated by GoReleaser. DO NOT EDIT.
cask "nexo" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "6a5654ed72bc2ea9e8d30b9bc638bc97591733c4dad5d5629288d4f5fb2a16b4"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "50063d38b5dc5004543d2299ceb1c731cc704d01eb8f137d83402e1777597e7c"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d5ad867565724f230f573effb47d51453fb4bcf5d9eed3fe623fd70b6111c540"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2cf79784bb03bb484205b785f03fc4208385e8977b8f0989170299e7bc6783ef"
      url "https://github.com/melvicsosa/nexo/releases/download/v#{version}/nexo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "nexo"
  desc "Package manager for AI development assets — skills, plugins and MCP servers"
  homepage "https://github.com/melvicsosa/nexo"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nexo"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nexo"]
    end
  end

  # No zap stanza required

end
