# This file was generated by GoReleaser. DO NOT EDIT.
cask "vopt" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "f1cfef029bdac0e9b6fe1c5e07bc721811c7d4060f4a6f397f748cdc67a2defb"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d37e46069ca164c7017c1d9e3de276cdc9515ccb3f92d936c4bd36be28cfb314"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "03147a7d43de2315ae94a13d5058d5b2952c8bb415916fe31a4177a609cf67a7"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "570d3b93648e38434298deb54f51ec0d028e1eb82dd366bae4a9b080368d8320"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vopt"
  desc "Compress videos with ffmpeg and capture their poster frame"
  homepage "https://github.com/melvicsosa/video-optimizer"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "vopt"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vopt"]
    end
  end

  # No zap stanza required

end
