# This file was generated by GoReleaser. DO NOT EDIT.
cask "vopt" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "9111db86a97774311a0b5ec18978fd6feb1ce5a79710e841d1b7f1529abc5ba8"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "69c55e8c1e1ab27ed169c204a3a37ce8b245d05b721a17169e71a54d946bb0f9"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4f159b78a4060cbd56693d62f32dfc1707b5449926058077c80ec69915fd06d4"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4b07d4a8b5fc02592e4ee282e9c5942a263bedb34074b9b0cfe0a4d71c3be70b"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vopt"
  desc "Compress videos with ffmpeg and capture their poster frame"
  homepage "https://github.com/melvicsosa/video-optimizer"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "vopt"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vopt"]
    end
  end

  # No zap stanza required

end
