# This file was generated by GoReleaser. DO NOT EDIT.
cask "vopt" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "0474fc1aaccc04cd834f7c4ffe9edab9317b86fa088a996744dfe46a763030de"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8c331fb3954549e85c5cc69672cdd35c84d36fc17373a70f0da3bac64a410cc5"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b07238c0e7096723a640dafa96bc484c25cf95001c0a9dcad0ab3d4c7ce0bea4"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5167d28331cef5a551cddc6d1a400362c26aecfe6ecf8cf12a907288d09e6d3a"
      url "https://github.com/melvicsosa/video-optimizer/releases/download/v#{version}/vopt_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vopt"
  desc "Compress videos with ffmpeg and capture their poster frame"
  homepage "https://github.com/melvicsosa/video-optimizer"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "ffmpeg",
    ]

  binary "vopt"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vopt"]
    end
  end

  # No zap stanza required

end
