# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillman < Formula
  desc "Cross-agent AI skill manager with a local UI"
  homepage "https://github.com/melvicsosa/skillman"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/melvicsosa/skillman/releases/download/v0.3.0/skillman_0.3.0_darwin_amd64.tar.gz"
      sha256 "a66e7251ad72d622588c985d0c26e0da6086613c3df2a08435479011cddff74a"

      define_method(:install) do
        bin.install "skillman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/melvicsosa/skillman/releases/download/v0.3.0/skillman_0.3.0_darwin_arm64.tar.gz"
      sha256 "7e2f7fff0ded42520c9c54d512ad637216d148a95813e8a93fbe82fa08851a25"

      define_method(:install) do
        bin.install "skillman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/melvicsosa/skillman/releases/download/v0.3.0/skillman_0.3.0_linux_amd64.tar.gz"
      sha256 "9e323f3244b91a191def070c4fa2e3ea4cf4feaa75927f9c772db5bc9d602f36"
      define_method(:install) do
        bin.install "skillman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/melvicsosa/skillman/releases/download/v0.3.0/skillman_0.3.0_linux_arm64.tar.gz"
      sha256 "560dc9973e224802ce49dd28db36a4bdd0385235ed0b181fea56787a5c7c6ebd"
      define_method(:install) do
        bin.install "skillman"
      end
    end
  end

  test do
    system "#{bin}/skillman", "version"
  end
end
