# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillman < Formula
  desc "Cross-agent AI skill manager with a local UI"
  homepage "https://github.com/melvicsosa/skillman"
  version "0.6.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/melvicsosa/skillman/releases/download/v0.6.2/skillman_0.6.2_darwin_amd64.tar.gz"
      sha256 "91d5ab1fe121dd8cace6f82aaba1cf9a3c1ff14c74684288b833e580549b9023"

      define_method(:install) do
        bin.install "skillman"
        bin.install "skillman-tray" if OS.mac?
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/melvicsosa/skillman/releases/download/v0.6.2/skillman_0.6.2_darwin_arm64.tar.gz"
      sha256 "33742cf716e3cae5786090163a2eb4a460d210df1024fe1f218ec530e0c9d5b1"

      define_method(:install) do
        bin.install "skillman"
        bin.install "skillman-tray" if OS.mac?
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/melvicsosa/skillman/releases/download/v0.6.2/skillman_0.6.2_linux_amd64.tar.gz"
      sha256 "f3adc0a6236aecfbf19cfbc2525c51cecad3783e5f8d2a049eb2e4628e067bc3"
      define_method(:install) do
        bin.install "skillman"
        bin.install "skillman-tray" if OS.mac?
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/melvicsosa/skillman/releases/download/v0.6.2/skillman_0.6.2_linux_arm64.tar.gz"
      sha256 "9529ea6e13170a85760ec1658d889c8d65960f0ed2742be443a9513bb6445285"
      define_method(:install) do
        bin.install "skillman"
        bin.install "skillman-tray" if OS.mac?
      end
    end
  end

  test do
    system "#{bin}/skillman", "version"
  end
end
